workflowVersion: 1.0.0
sources:
    merge-code-samples-into-spec:
        inputs:
            - location: registry.speakeasyapi.dev/livepeer-8mq/livepeer-ai/livepeer-ai-oas
        overlays:
            - location: registry.speakeasyapi.dev/livepeer-8mq/livepeer-ai/code-samples-typescript-livepeer-ts:main
        output: ./openapi.yaml
targets: {}
